sudo: true
language: c

osx_image: xcode8

#run builds for linux and osx. will add windows shortly
os:
#  - osx add osx back when travis fixes their mac os scaling problems.
  - linux

#run builds on both gcc and clang
compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -qq cppcheck

#execute build
script:
  #build checksums
  - git clone https://github.com/awslabs/aws-checksums.git
  - mkdir checksums-build && cd checksums-build
  - cmake ../aws-checksums
  - make -j 12 && make test
  - cd ..

  #build aws-c-common
  - git clone https://github.com/awslabs/aws-c-common.git
  - mkdir common-build && cd common-build
  - cmake ../aws-c-common
  - make -j 12 && make test
  - cd ..

  #build aws-c-event-stream
  - cppcheck --enable=all --std=c99 --language=c --suppress=unusedFunction -I include aws-checksums/include aws-c-common/include --force --error-exitcode=-1 ./
  - mkdir build
  - cd build
  - cmake -Daws-checkums_DIR="./checksums-build" -Daws-c-common_DIR="./common-build" ..
  - make && make test

